# Generated by Django 4.2.27 on 2026-01-15 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_couponmodel_used_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponmodel',
            old_name='discount_pecent',
            new_name='discount_percent',
        ),
    ]
