# Generated by Django 4.2.27 on 2026-01-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['-created_date']},
        ),
    ]
